### ISSUE TITLE
some bugs in BuildModel class

### ISSUE THREAD

**Issue by Pellarin** [salilab/pmi#100]
1) gmm_models_directory is not specified, therefore the gmms are constructed anyway
2) `if em_txt_file_name is " " or em_txt_file_name is None` from the dict one can pass a None or empty string, that option was not included
3) `if num_components < 0:`
`num_components=number_of_residues/abs(num_components)`
Didn't we say to use residue per gaussian when the num_components was negative?

**Comment by Pellarin** [comment]
closed by ffdc822cff8d33817a203c04712799646e1e7708

**Comment by cgreenberg** [comment]
If you setup BuildModel using the ComponentTopology class (which should be the primary format now), you don't have to pass the GMM directory when you setup BuildModel - the directory is stored internally so when you call ComponentTopology.gmm_file, it gives you the full path.
We also made it so it automatically reads the GMM file if it's already created, otherwise it creates it. Again, only for the new ComponentTopology class:

``` python
                if em_num_components==0:
                    read_em_files=False
                    include_res0=False
                else:
                    if (not os.path.isfile(em_txt_file_name)) or force_create_gmm_files:
                        read_em_files=False
                        include_res0=True
                    else:
                        read_em_files=True
                        include_res0=False
```

We should probably use "force_sample_gmms" as a flag instead of using the directory=None thing. But I guess we need to pass the directory in the case of using the legacy format.

Also, I thought we decided the primary use case was using residues_per_gaussian rather than an absolute number?

**Comment by cgreenberg** [comment]
Maybe easier if we make BuildModel1 the legacy class and separate the interfaces...

**Comment by Pellarin** [comment]
Yes, but it should be back compatible, otherwise many projects will die!!!

On Tue, Nov 25, 2014 at 5:14 PM, Charles Greenberg <notifications@github.com

**Comment by cgreenberg** [comment]
OK I'll do that. BuildModel() is the new interface, BuildModel1() will go back to original interface, but marked deprecated.

**Comment by benmwebb** [comment]
I believe these issues are no longer present in modern PM.
