### ISSUE TITLE
Issue in restraints/stereochemistry.py

### ISSUE THREAD

**Issue by Pellarin** [salilab/pmi#144]
@cgreenberg  The following lines in restraints/stereochemistry.py

```
        if (  isinstance(included_objects, IMP.pmi.topology.SystemBase)
             or isinstance(included_objects, IMP.pmi.topology.Residue)
             or ( type(included_objects) is list and ( isinstance(included_objects[0], IMP.pmi.topology.SystemBase) or isinstance(included_objects[0], IMP.pmi.topology.Residue)) )
             or ( type(included_objects) is set) ):
```

one should have `IMP.pmi.topology.Residue` -> `IMP.pmi.topology.TempResidue` according to recent class name changes

**Comment by benmwebb** [comment]
BTW, `isinstance` takes a tuple of classes as its second argument, so you can write `isinstance(x, (A, B))` rather than `isinstance(x, A) or isinstance(x, B)`. Also explicitly checking for type==list or set isn't a good idea since Python uses duck typing. Check instead for the methods you want to use (for example `__getslice__` and `difference`)

**Comment by cgreenberg** [comment]
A nice way to check for list, set, or so on, is to check if you can iterate with `if hasattr(spec,'__iter__')`

**Comment by benmwebb** [comment]
Indeed, although that's no good in this case, since you explicitly use the `[]` operator (`__getitem__` method) later in the 'if'. Something can be iterable but not indexable (e.g. a generator object).

**Comment by Pellarin** [comment]
OK, but still, one should have `IMP.pmi.topology.Residue` -> `IMP.pmi.topology.TempResidue`, am I right?

**Comment by cgreenberg** [comment]
Yep fixing now
