### ISSUE TITLE
Behaviour of represented molecule set is inconsistent during model building

### ISSUE THREAD

**Issue by shanot** [salilab/pmi#195]
see comments in the test added in commit ed70f258e27edae9e837cff5150a4a838f43e93a

**Comment by cgreenberg** [comment]
Yes, looks like the problem is that when you call `mol[:]` it builds a new OrderedSet, which has fewer items after `build()` since a bunch of residues are now the same (e.g. if you only build a res10 bead, residues 1-10 all point to the same hierarchy). But the `mol.represented` object is not rebuilt so it still thinks res1,res2,... are all different. I'll update it so mol.represented is internal (`mol._represented`) and add a new function `mol.get_represented()` which will be refreshed each time.

**Comment by shanot** [comment]
fb638c8099c6f78d0bfd75aa5dfab70ededce742

I have added a new test (`test_molecule_set_behaviour2`) that fails.

The `build` method still produces inconsistent set behaviour.

sam

**Comment by shanot** [comment]
1931d5c0632ce5a6aad50db6d496354fbf5e8ff1 and 12fa17a333177590b1222c6991bc3f38d62dd12e should have fixed the way TempResidues are hashed, which enabled our test to pass.
It would be nice to ensure that the elements that are hashed are made immutable to ensure such issue do not arise in the future.

**Comment by cgreenberg** [comment]
Yes, that makes sense, thanks for fixing. yeah it's tricky because we want the temp residue handles to still work after building even though the building process can be destructive.
