### ISSUE TITLE
IMP.core.Gaussian.get_is_setup(p) is not working as expected

### ISSUE THREAD

**Issue by procyon777** [salilab/pmi#205]
Please see my commit.

https://github.com/salilab/pmi/commit/57d58e9116e89304f2e523b6027c8a9c0b2faf9d

Currently "IMP.core.Gaussian.get_is_setup(p)" does not detect GMM + Gaussian beads correctly as I expected.

**Comment by benmwebb** [comment]
Best solution would be for you to provide a minimal example that actually demonstrates the problem as a (failing) test case. Then we can fix it and the test case will ensure it stays fixed. Hacking the code as in 57d58e9 is likely to just introduce more bugs down the line.

Without a test case it's pretty hard for me to see what the problem is, but most likely `p` is not really a Gaussian particle. Something would have to be deeply wrong in IMP for `IMP.core.Gaussian.get_is_setup` to fail.

**Comment by procyon777** [comment]
Many thanks.  The example is in github.com/salilab/npc
I need to update a simple test case, and let you know when it is ready.
- SJ

**Comment by benmwebb** [comment]
Just put "relates #205" in the commit message for the test case, and it'll show up here automatically.

**Comment by Pellarin** [comment]
I suspect p is not a particle but a hierarchy, SJ. Try the following:

IMP.core.Gaussian.get_is_setup(p.get_particle())

# Riccardo Pellarin, PhD

Institut Pasteur
CNRS UMR 3528
25, rue du Docteur Roux
75724 Paris Cedex 15, France
riccardo.pellarin@pasteur.fr
+33 (0)1 44 38 93 63

**Comment by procyon777** [comment]
Thanks Riccardo!  However both IMP.core.Gaussian.get_is_setup(p)  and  IMP.core.Gaussian.get_is_setup(p.get_particle()) returned the same values.

After digging out this issue more deeply, I realized that actually all the beads (where there is no pdb template available) are assigned as Gaussian particles as below.  That is why it is "True" for beads, which is completely opposite to my need.  Here I need to exclude only "_gaussian_*", so I believe that current script is good enough for my purpose.  I'll leave it as is.  Thanks a lot everyone!

**Comment by benmwebb** [comment]
> I suspect p is not a particle but a hierarchy, SJ. Try the following: IMP.core.Gaussian.get_is_setup(p.get_particle())

Any Decorator should implicitly convert to Particle, so that shouldn't make any difference.

**Comment by Pellarin** [comment]
OK, true, then you can try the following:

IMP.core.Gaussian.get_is_setup(p) and not IMP.atom.Hierarchy.get_is_setup
(p)

should return True only for _gaussian_ stuff.

# Riccardo Pellarin, PhD

Institut Pasteur
CNRS UMR 3528
25, rue du Docteur Roux
75724 Paris Cedex 15, France
riccardo.pellarin@pasteur.fr
+33 (0)1 44 38 93 63

**Comment by procyon777** [comment]
Sorry still not working even with what you suggested.  It excludes the beads, but it also excludes '_gaussian__'.  It is because '_gaussian__' is defined in the Hierarchy.  Can we keep the script as is, at least for now?  My trick using p.get_name()[0:10] == '_gaussian_' magically works fine here...

**Comment by Pellarin** [comment]
The magic thing is really bad, sorry, and we're trying not to use this code
based on particle names anymore. It's easy to break this code!
I understand that you want quickly hack the code so that it works for your
special case, but you have to consider that there are other people using it!

So,  either you write this hacking code somewhere else. For instance, you
can create your own Representation class
inheriting from IMP.pmi.representation.Representation. You can redefine
your methods and hacking whatever you want,
and still keep track of changes occurring elsewhere, if the code is updated
in the repository
(but not in the redefined function! see for instance
http://stackoverflow.com/questions/9834076/redefinition-of-class-method-in-python
).
Or you write your functions in your script.

Otherwise, we have to force ourselves to access to particle attributes
through decorators...

 _gaussian_ are not Fragment (or they shouldn't be), instead Beads may be
Fragments or Residues. Try the following:

IMP.core.Gaussian.get_is_setup(p) / not ( IMP.atom.Fragment.get_is_setup(p)
or IMP.atom.Residue.get_is_setup(p) )

# Riccardo Pellarin, PhD

Institut Pasteur
CNRS UMR 3528
25, rue du Docteur Roux
75724 Paris Cedex 15, France
riccardo.pellarin@pasteur.fr
+33 (0)1 44 38 93 63

**Comment by benmwebb** [comment]
> My trick using p.get_name()[0:10] == 'gaussian' magically works fine here...

It won't work for long. Particle names in IMP are for humans only, so the user can set them to any arbitrary value.

**Comment by procyon777** [comment]
if (IMP.core.Gaussian.get_is_setup(p)) and not (IMP.atom.Fragment.get_is_setup(p) or IMP.atom.Residue.get_is_setup(p)):
                    continue

This works perfect!  Riccardo, thanks a lot!
