### ISSUE TITLE
Fix GaussianEMRestraint to work with PMI2

### ISSUE THREAD

**Issue by benmwebb** [salilab/pmi#243]
Several users have reported that the GaussianEMRestraint, which works fine with PMI1, fails to pull the model into the map with PMI2. This should be addressed if PMI2 is to truly replace PMI1.

**Comment by Pellarin** [comment]
GaussianEMRestraint should work fine, but one has to caliber the weight correctly. It would be nice to see one example.
However, now we have the bayesian restraint in https://gitlab.pasteur.fr/rpellari/bayesianem which should account better for the weight.

**Comment by benmwebb** [comment]
> GaussianEMRestraint should work fine

Right, but people keep telling me otherwise. ;)

> but one has to caliber the weight correctly. It would be nice to see one example.

Are you volunteering to write such an example? I don't recall any of the EM guys making a big deal out of the weight before. How would you calibrate it?

> now we have the bayesian restraint in https://gitlab.pasteur.fr/rpellari/bayesianem

Any reason why we can't merge that into the main IMP.em module?

**Comment by grandrea** [comment]
Hello,

Apologies for reviving/joining in this thread... I believe we are experiencing the problem mentioned here. 
In our hands, when one uses the BuildSystem macro with PMI2 in conjunction with the topology reader only the flexible beads generated for regions not covered by the pdb file are included in the GMM restraint, as shown by the selection in the rmf.

I believe this has something to do with the setup_particles_as_densities option in add_representation, since if I enable this using add_representation everything gets selected for the GMM. The problem to me seems to be the fact that the GMM restraint needs DENSITIES, which I can't seem to generate for regions covered by the pdb file when using BuildSystem and TopologyReader.

I am quite new with IMP, so it may very well be a mistake or a misunderstanding, in which case I apologise....

I attach a test case...
[gmm_test_case.tar.gz](https://github.com/salilab/pmi/files/2954212/gmm_test_case.tar.gz)

**Comment by benmwebb** [comment]
> In our hands, when one uses the BuildSystem macro with PMI2 in conjunction with the topology reader only the flexible beads generated for regions not covered by the pdb file are included in the GMM restraint

This sounds like an entirely unrelated problem. But by all means open a separate issue for it and I can take a look.

**Comment by grandrea** [comment]
thank you for your time! I will do that then

**Comment by benmwebb** [comment]
Nobody has complained about this for a while, closing for now.
