### ISSUE TITLE
GaussianEMRestraint not selecting regions covered by pdb file when using TopologyReader

### ISSUE THREAD

**Issue by grandrea** [salilab/pmi#248]
Hello,

In our hands, when one uses the BuildSystem macro with PMI2 in conjunction with the topology reader only the flexible beads generated for regions not covered by the pdb file are included in the GMM restraint, as shown by the selection in the rmf.

I believe this has something to do with the setup_particles_as_densities option in add_representation, since if I enable this using add_representation instead of using TopologyReader everything gets selected for the GMM. 
The problem to me seems to be the fact that the GMM restraint needs DENSITIES, which I can't seem to generate for regions covered by the pdb file when using BuildSystem and TopologyReader.

I am quite new with IMP, so it may very well be a mistake or a misunderstanding, in which case I apologise....

I have tested this with imp 2.10 and 2.10.1.

I attach a test case...

Thank you

Andrea
[gmm_test_case.tar.gz](https://github.com/salilab/pmi/files/2956099/gmm_test_case.tar.gz)

**Comment by benmwebb** [comment]
Everything looks fine to me when I run your script. What do you mean by

> only the flexible beads generated for regions not covered by the pdb file are included in the GMM restraint

The EM restraint doesn't act on beads or structure; it acts on Gaussians. These are considered an alternate representation of the system and should be generated by `TopologyReader`. And indeed if I print `em_components` in your script I see

`["1-10_bead", "11_bead", "Density #0", "Density #1", "Density #2", "Density #3", "Density #4", "Density #5", "Density #6", "Density #7", "Density #8", "Density #9", "Density #10", "Density #11", "Density #12", "Density #13", "Density #14", "Density #15", "Density #16", "Density #0", "Density #1", "Density #2", "Density #3", "Density #4", "Density #5", "Density #6", "Density #7", "Density #8", "Density #9", "Density #10", "Density #11", "Density #0", "Density #1", "Density #2", "Density #3", "Density #4", "Density #5", "Density #6", "Density #7", "Density #0", "Density #1", "Density #2", "Density #3", "Density #4", "Density #5", "Density #6", "Density #7", "Density #0", "Density #1", "457-466_bead", "467-476_bead", "477-486_bead", "487-496_bead", "497-506_bead", "507-516_bead", "517-526_bead", "527-536_bead", "537-540_bead"]`

i.e. 58 Gaussians, which is about what I would expect for a 540-residue protein using 1 Gaussian per 10 residues. What do you mean by "selection in the rmf"?

**Comment by grandrea** [comment]
I really appreciate you taking the time. Like I said, it may be a trivial misunderstanding.
If you open the rmf in chimera, you see that only the beads corresponding to the flexible regions are highlighted when selecting the GaussianEMrestraint, and those appear to drive the sampling into the gmm (input/gmm2.mrc)...

**Comment by benmwebb** [comment]
> If you open the rmf in chimera, you see that only the beads corresponding to the flexible regions are highlighted when selecting the GaussianEMrestraint

Ah, I see how that could be confusing. Your protein is represented at three different (and simultaneous) scales: fine beads (1 residue per bead); coarse beads (10 residues per bead) and Gaussians (10 residues per Gaussian). Chimera only shows the fine beads and coarse beads - it doesn't know how to show Gaussians. The EM restraint only acts on the Gaussians.  If you look at the RMF file with `rmf_show` or in the Chimera RMF Hierarchy view you'll see that the particles for your flexible regions are doing double duty as both the coarse beads *and* the Gaussians (they are labeled "Res 10 Densities 10"). So when you click on the restraint, Chimera tries to show you the Gaussians but can't find them and gets confused and shows you the coarse beads. But it can't do that for the structured regions, since there the Gaussians and coarse beads are actually separate particles. I don't recall the reason for sharing the particles in this way but perhaps @cgreenberg can clarify?

> and those appear to drive the sampling

Pretty sure that isn't the case. As far as I can see the restraint is working correctly here.

**Comment by grandrea** [comment]
Thank you for the follow up, that clarifies it. So it's just the way a multiscale rmf is displayed in chimera (and perhaps some of the weights and starting positions we were using to test this made it appear the sampling was driven by the loops). Cheers!

**Comment by cgreenberg** [comment]
We decorated the particles as Gaussians because it seemed easier/simpler than making a new particle for each Gaussian and then constraining them to stay on top of the underlying XYZs. But other than that there's no reason why we couldn't change it, especially if it makes display in Chimera a bit better (or someone could change Chimera!).
