### ISSUE TITLE
Start packing more information in the RMF files

### ISSUE THREAD

**Issue by cgreenberg** [salilab/pmi#88]
We need the nuisances in there, and the full CrossLink restraints if that's possible. And, more importantly, the restraint names don't really have useful information (certainly for the mediator complex, they don't indicate which 'module' they're from, so you have to dig this out of the stat file). All of this makes reading data from RMFs a bitch.

**Comment by benmwebb** [comment]
Spooky - I was just about to open a similar issue. The Nup84 RMFs look like they have basic cross link information in them, but they should really have pointers to the input PDBs and other input data too. In fact, one could almost imagine regenerating the bulk of a PMI script semi-automatically by reading the RMF file it generates.

Please also take a look at John's proposed mmCIF extensions. We want to make sure we can store this information in them too.

**Comment by cgreenberg** [comment]
YES! You should be able to restore everything from an RMF file. It's killing me. Can we store any restraint at all in an RMF file? We currently just have harmonic restraints stored in lieu of crosslinks because those can be viewed easily for quick debugging (chimera draws little squigglies). What would be nice is if RMF could handle a restraint that has lots of input particles, but only two specific ones used for drawing...

Also I'm guessing it's easy to write nuisances to the RMF as well? They aren't a part of the main protein hierarchy though.

**Comment by benmwebb** [comment]
Sure, you can in principle store a restraint that takes as input any number of particles. See http://integrativemodeling.org/rmf/decoratorsattributes.html#feature

If this is inadequate, open an RMF issue - it can certainly be extended (e.g. might be useful to have a restraint type in there too).

I haven't looked at the IMP code to store restraints in RMF files yet, so it's possible IMP doesn't take full advantage of RMF here.

Max writes his nuisances to a separate RMF, IIRC - but you can check on that with @shruthivis. But there's no reason why they couldn't be stored in the RMF too (open an issue too so we don't forget). It's just a handful of numbers per particle. You'd have to think of a sensible way to add them to the hierarchy though in order to store them in the RMF, since everything in the RMF is a hierarchy.

**Comment by shruthivis** [comment]
Yes Max writes ISD particles to a separate RMF file, with a different
hierarchy. The reading/writing of the physical particles and ISD particles
have to be sync'ed frame by frame, which may introduce errors. So it can be
helpful to have them all in one RMF.

**Comment by benmwebb** [comment]
Most restraint information should now be stored in RMF files.
